### ISSUE TITLE
Stop Installation on MySQL page

### ISSUE THREAD

**Issue by aliqasemzadeh** [fusioncms/fusioncms#759] opened 2021-07-15 14:40 UTC
Hi
When I want to install FCMS in mysql setup page i get no error and it stop installation there.

**Comment by huiyang** [comment] 2021-07-16 15:35
Please mention which version you are using and follow/use the bug reporting format/template.

**Comment by aliqasemzadeh** [comment] 2021-07-25 13:26
@huiyang 
6.0.0 Beta 10

**Comment by huiyang** [comment] 2021-07-27 03:31
The bug is caused by wrong name of the input field, please refer to this to debug:
https://github.com/antwebstudio/fusion-cms/commit/32db27259c535e10e662812e091774fb94286924

**Comment by aliqasemzadeh** [comment] 2021-07-27 03:34
@huiyang 
How can i fix it?

**Comment by huiyang** [comment] 2021-07-27 07:15
I have already show you in my previous reply.

**Comment by aliqasemzadeh** [comment] 2021-07-27 15:23
@huiyang 
Please make pull request and accept it.

**Comment by huiyang** [comment] 2021-07-28 13:00
No, since it is a outdated version.
You may use my forked version or fork yourself another repo to make changes.

**Comment by aliqasemzadeh** [comment] 2021-07-28 16:17
@huiyang Please give me link.

**Comment by huiyang** [comment] 2021-07-29 09:26
I already gave you in previous comment....

**Comment by K-E-L** [comment] 2021-09-22 18:48
closed by fusioncms/cms#226

**Closed as completed by K-E-L** 2021-09-22 18:48 UTC
Labels: Bug
